Avalonia ship groups improvements 2
ElectronicObserverEN/ElectronicObserver pull request #472
Opened 2024-06-08 09:00 UTC by myangelkamikaze

Continuing from #470

- [ ] Get rid of WinForms dialogs
  - [x] Text input dialog
  - [ ] Text select dialog
  - [ ] Ship group filter dialog
  - [ ] Ship group CSV export dialog
- [x] Add data grid settings
  - [x] Header/row height
- [x] Background colors

Notes:
- new dialogs need a window reference, so they have to be done in WPF instead of Avalonia for now, but the dialog library supports both WPF and Avalonia, so a migration later should be fairly simple

2024-06-13 16:18 UTC, Jebzou commented
Weird behavior after closing a dialog

https://github.com/ElectronicObserverEN/ElectronicObserver/assets/22751386/405c0249-d555-471b-bf97-81611aa9b15e

2024-06-13 16:24 UTC, Jebzou requested changes
Behavior is not the same as old groups, is that intended ?


https://github.com/ElectronicObserverEN/ElectronicObserver/assets/22751386/86d25128-feee-4ce8-ace7-0769ca8a3635

2024-06-14 04:58 UTC, myangelkamikaze commented
> Weird behavior after closing a dialog

Should be fixed.

> Behavior is not the same as old groups, is that intended ?

It wasn't really intended, it was just less work to do it this way. But I added the logic to match the old group behavior now.

2024-06-14 15:07 UTC, Jebzou approved these changes

2024-06-14 15:13 UTC, merged